
- name: disable swap
  become: yes
  sysctl:
    # http://askubuntu.com/questions/103242/is-it-safe-to-turn-swap-off-permanently
    name: vm.swappiness
    value: 10
    state: present

- name: configure timezone
  become: yes
  timezone:
    name: UTC
