
- name: Upload Configs
  import_tasks: configs.yml
  tags:
    - never
    - configs

- name: Backup
  shell: "cd '{{actual_configs}}' && ./bin/tt_backup"
  tags:
    - never
    - backup

- name: Switch versions
  import_tasks: switch_versions.yml
  tags:
    - never
    - switch
